### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by Baileyswu** [DeepTrial/ECNU-Dissertations-Latex-Template#2]
感谢您的分享！对照着前几届的毕业论文，模版中有几个小问题希望您有空可以修复一下：
1. 每一章的第一页没有页眉
2. 章节标题与上边距离过大
3. 图形、表格、目录的页面，首行标题过大。

**Comment by DeepTrial** [comment]
ok,我会关注一下这些问题的。

不过，我发现前几届师兄师姐的论文格式都有细微的差异。我实在搞不清标准的格式是什么样的了...

**Comment by Baileyswu** [comment]
嗯，我又结合了[ECNU-Paper-Template](https://github.com/c834606877/ECNU-Paper-Template)里的做法fix了一下。

**Comment by bale512** [comment]
> 嗯，我又结合了[ECNU-Paper-Template](https://github.com/c834606877/ECNU-Paper-Template)里的做法fix了一下。

hxd，能发个pr让我看看你怎么修得嘛？我也发现你说得问题

**Comment by Baileyswu** [comment]
> > 嗯，我又结合了[ECNU-Paper-Template](https://github.com/c834606877/ECNU-Paper-Template)里的做法fix了一下。
> 
> hxd，能发个pr让我看看你怎么修得嘛？我也发现你说得问题

hjm, 直接用我的[repo](https://github.com/Baileyswu/ECNU-thesis-template)呗
